### PR TITLE
busybox modprobe lacks zstd support, fix this

### PR DESCRIPTION
**Pull request by majst01**
Newer Ubuntu Kernels built their kernel modules compressed with zstd, this actually prevents the csi driver to load the required kernel module:

```bash
2024-01-09T16:56:14.359520701+01:00 stdout F filename:       /lib/modules/6.6.10-060610-generic/kernel/drivers/nvme/host/nvme-tcp.ko.zst
2024-01-09T16:56:14.366091503+01:00 stderr F modprobe: can't load module nvme_tcp (kernel/drivers/nvme/host/nvme-tcp.ko.zst): invalid module format
```
This is because `modprobe` is `busybox`.

With this PR `kmod` is installed which depends on zstd-libs and provides zstd support.

### CODE REVIEW

**Comment by mwennrich** [comment]
loading of the module with this PR now works:

```
$ k logs lb-csi-node-xgwsw -c init-nvme-tcp
filename:       /lib/modules/6.6.10-060610-generic/kernel/drivers/nvme/host/nvme-tcp.ko.zst
license:        GPL v2
srcversion:     A5B1C9B60F86F438D4705E4
depends:        nvme-core,nvme-fabrics
retpoline:      Y
intree:         Y
name:           nvme_tcp
vermagic:       6.6.10-060610-generic SMP preempt mod_unload modversions
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        79:84:5D:77:A6:12:9D:32:D6:25:11:C2:ED:F6:A4:53:4D:93:E4:32
sig_hashalgo:   sha512
signature:      1B:B9:1E:B9:FF:01:B1:D1:54:A1:09:B7:EF:77:58:C8:D5:0D:E4:00:
                (...)
```

previously (without the PR):

```
k logs -n kube-system lb-csi-node-l677z -c init-nvme-tcp
filename:       /lib/modules/6.6.10-060610-generic/kernel/drivers/nvme/host/nvme-tcp.ko.zst
```

mounting of volumes still doesn't work:

```
events:
24s         Normal    SuccessfulAttachVolume   pod/busybox-0                              AttachVolume.Attach succeeded for volume "pvc-5c52390c-67ab-4fe8-99c2-ae0092291a55"
4s          Warning   FailedMount              pod/busybox-0                              MountVolume.MountDevice failed for volume "pvc-5c52390c-67ab-4fe8-99c2-ae0092291a55" : rpc error: code = Unknown desc = OS error: no local block device for volume e28db617-dbcc-4bb1-a318-8f4d88de07b0
```

```
dmesg:
[Wed Jan 10 10:31:11 2024] nvme_fabrics: found same hostid 2b0bf3a6-721f-47f6-9fd7-ca3ffe410c1f but different hostnqn nqn.2019-09.com.lightbitslabs:host:shoot--p4jxn2--mwentest-group-0-8558f-j992z.node
```




```
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:09.315097+00:00" level=info msg="server request payload logged as grpc.request.content field" grpc.method=NodeStageVolume grpc.request.content="volume_id:\"mgmt:10.131.44.1:443,10.131.44.2:443,10.131.44.3:443|nguid:e28db617-dbcc-4bb1-a318-8f4d88de07b0|proj:cd4eac58-46a5-4a31-b59f-2ec207baa817|scheme:grpcs\" staging_target_path:\"/var/lib/kubelet/plugins/kubernetes.io/csi/csi.lightbitslabs.com/def1d0cfdc968ea5a0dd2cdb5cce2ccd04bed7dc0740274be20a5dcba3218ce3/globalmount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > secrets:<key:\"jwt\" value:\"eyJhbGciOiJSUzI1NiIsImtpZCI6ImNkNGVhYzU4LTQ2YTUtNGEzMS1iNTlmLTJlYzIwN2JhYTgxNzpyb290IiwidHlwIjoiSldUIn0.eyJpc3MiOiJkdXJvcy1jb250cm9sbGVyIiwic3ViIjoic2hvb3QtLXA0anhuMi0tbXdlbnRlc3QiLCJleHAiOjE3MDU1MDE2NTEsImlhdCI6MTcwNDgxMDQ1MSwianRpIjoiYjNlYWY1OWUtNmY0Ny00NmM0LTllOTEtYmUxODlkYTk1MWVhIiwicm9sZXMiOlsiY2Q0ZWFjNTgtNDZhNS00YTMxLWI1OWYtMmVjMjA3YmFhODE3OmFkbWluIl19.Qpbx12I2ZrTPEKZlHvwTLM8K-ex-0X4OOgt6keoNqd6VlTuBe4bQ6UxjcSlQFJKPsHst8XSnV1Ro00ChAZtunxlue-ndXcZbABInQxuYngeQJXTih5DiEAokwF-giKLycValzoR-TaikTNSkmjxXaoVorzXBrE_WkJqw5dTgPdjmQF7wgTdnMTothQhJOMAerUVR4meHSNE82RRzg968PyzRAyRPhi5P2Canp7oumYwnhJcqlswl0TEm6syokaZqMuddtebTaiSuAadmO0055liJ_oYq8UBk5nz-NsJycuitnXr0D2SW-loPlEnLbayiYJ1IeBJ2BR1o9JgRZtK-_w\" > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1704875545056-7667-csi.lightbitslabs.com\" > " grpc.request.deadline="2024-01-10T09:33:09Z" grpc.service=csi.v1.Node grpc.start_time="2024-01-10T09:31:09Z" node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node peer.address=@ role=node span.kind=server system=grpc
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:09.324866+00:00" level=info msg="client request payload logged as grpc.request.content" clnt-id=0c56r1d grpc.method=GetVolume grpc.request.content="UUID:\"e28db617-dbcc-4bb1-a318-8f4d88de07b0\"  projectName:\"cd4eac58-46a5-4a31-b59f-2ec207baa817\"" grpc.service=lightbits.api.duros.v2.DurosAPI node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node role=node span.kind=client system=grpc
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:09.327783+00:00" level=info msg="client response payload logged as grpc.response.content" clnt-id=0c56r1d grpc.method=GetVolume grpc.response.content="state:Available  protectionState:FullyProtected  replicaCount:3  nodeList:\"1602ec84-fb45-5cf6-8a2f-641e16c1aa61\"  nodeList:\"fa0ebc2e-0f18-5a96-9d45-0516ad68f1b0\"  nodeList:\"aa67a975-bbf5-5c43-85bc-28503bfbe956\"  UUID:\"e28db617-dbcc-4bb1-a318-8f4d88de07b0\"  nsid:352  acl:{values:\"nqn.2019-09.com.lightbitslabs:host:shoot--p4jxn2--mwentest-group-0-8558f-j992z.node\"}  compression:\"true\"  size:1073741824  name:\"pvc-5c52390c-67ab-4fe8-99c2-ae0092291a55\"  rebuildProgress:\"None\"  statistics:{compressionRatio:1  totalCompressionRatio:1}  IPAcl:{values:\"ALLOW_ANY\"}  ETag:\"6\"  sectorSize:4096  projectName:\"cd4eac58-46a5-4a31-b59f-2ec207baa817\"  qosPolicyUUID:\"a92b56c1-e916-4396-8774-d34d3acf7e8a\"  qosPolicyName:\"no-limit-policy\"  primaryNodeUUID:\"1602ec84-fb45-5cf6-8a2f-641e16c1aa61\"" grpc.service=lightbits.api.duros.v2.DurosAPI node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node role=node span.kind=client system=grpc
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:09.327936+00:00" level=info msg=entry backend=dsc call-id=1 hostnqn="nqn.2019-09.com.lightbitslabs:host:shoot--p4jxn2--mwentest-group-0-8558f-j992z.node" method=LBVolEligible node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node role=node vol-uuid=e28db617-dbcc-4bb1-a318-8f4d88de07b0
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:09.327962+00:00" level=info msg=exit backend=dsc call-id=1 code=OK hostnqn="nqn.2019-09.com.lightbitslabs:host:shoot--p4jxn2--mwentest-group-0-8558f-j992z.node" method=LBVolEligible node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node role=node vol-uuid=e28db617-dbcc-4bb1-a318-8f4d88de07b0
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:09.353582+00:00" level=info msg=entry backend=dsc call-id=2 hostnqn="nqn.2019-09.com.lightbitslabs:host:shoot--p4jxn2--mwentest-group-0-8558f-j992z.node" method=Attach node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node role=node vol-uuid=e28db617-dbcc-4bb1-a318-8f4d88de07b0
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:09.353619+00:00" level=debug msg="creating DSC config file '/etc/discovery-client/discovery.d/e28db617-dbcc-4bb1-a318-8f4d88de07b0'..." backend=dsc hostnqn="nqn.2019-09.com.lightbitslabs:host:shoot--p4jxn2--mwentest-group-0-8558f-j992z.node" node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node role=node
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:09.353774+00:00" level=info msg=exit backend=dsc call-id=2 code=OK hostnqn="nqn.2019-09.com.lightbitslabs:host:shoot--p4jxn2--mwentest-group-0-8558f-j992z.node" method=Attach node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node role=node vol-uuid=e28db617-dbcc-4bb1-a318-8f4d88de07b0
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:09.354107+00:00" level=debug msg="didn't find uuid: e28db617-dbcc-4bb1-a318-8f4d88de07b0 in effDevices: [/dev/nvme0n1 /dev/nvme1n1]" node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node role=node
(...)
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:12.274036+00:00" level=debug msg="didn't find uuid: e28db617-dbcc-4bb1-a318-8f4d88de07b0 in effDevices: [/dev/nvme0n1 /dev/nvme1n1]" node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node role=node
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:12.274086+00:00" level=error msg="finished unary call with code Unknown" error="rpc error: code = Unknown desc = OS error: no local block device for volume e28db617-dbcc-4bb1-a318-8f4d88de07b0" grpc.code=Unknown grpc.method=NodeStageVolume grpc.request.deadline="2024-01-10T09:33:09Z" grpc.service=csi.v1.Node grpc.start_time="2024-01-10T09:31:09Z" grpc.time_ms=2959.005 node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node peer.address=@ role=node span.kind=server system=grpc
lb-csi-node-xgwsw lb-csi-plugin time="2024-01-10T09:31:12.849069+00:00" level=info msg="server request payload logged as grpc.request.content field" grpc.method=NodeStageVolume grpc.request.content="volume_id:\"mgmt:10.131.44.1:443,10.131.44.2:443,10.131.44.3:443|nguid:e28db617-dbcc-4bb1-a318-8f4d88de07b0|proj:cd4eac58-46a5-4a31-b59f-2ec207baa817|scheme:grpcs\" staging_target_path:\"/var/lib/kubelet/plugins/kubernetes.io/csi/csi.lightbitslabs.com/def1d0cfdc968ea5a0dd2cdb5cce2ccd04bed7dc0740274be20a5dcba3218ce3/globalmount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > secrets:<key:\"jwt\" value:\"eyJhbGciOiJSUzI1NiIsImtpZCI6ImNkNGVhYzU4LTQ2YTUtNGEzMS1iNTlmLTJlYzIwN2JhYTgxNzpyb290IiwidHlwIjoiSldUIn0.eyJpc3MiOiJkdXJvcy1jb250cm9sbGVyIiwic3ViIjoic2hvb3QtLXA0anhuMi0tbXdlbnRlc3QiLCJleHAiOjE3MDU1MDE2NTEsImlhdCI6MTcwNDgxMDQ1MSwianRpIjoiYjNlYWY1OWUtNmY0Ny00NmM0LTllOTEtYmUxODlkYTk1MWVhIiwicm9sZXMiOlsiY2Q0ZWFjNTgtNDZhNS00YTMxLWI1OWYtMmVjMjA3YmFhODE3OmFkbWluIl19.Qpbx12I2ZrTPEKZlHvwTLM8K-ex-0X4OOgt6keoNqd6VlTuBe4bQ6UxjcSlQFJKPsHst8XSnV1Ro00ChAZtunxlue-ndXcZbABInQxuYngeQJXTih5DiEAokwF-giKLycValzoR-TaikTNSkmjxXaoVorzXBrE_WkJqw5dTgPdjmQF7wgTdnMTothQhJOMAerUVR4meHSNE82RRzg968PyzRAyRPhi5P2Canp7oumYwnhJcqlswl0TEm6syokaZqMuddtebTaiSuAadmO0055liJ_oYq8UBk5nz-NsJycuitnXr0D2SW-loPlEnLbayiYJ1IeBJ2BR1o9JgRZtK-_w\" > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1704875545056-7667-csi.lightbitslabs.com\" > " grpc.request.deadline="2024-01-10T09:33:12Z" grpc.service=csi.v1.Node grpc.start_time="2024-01-10T09:31:12Z" node=shoot--p4jxn2--mwentest-group-0-8558f-j992z.node peer.address=@ role=node span.kind=server system=grpc
```

**Comment by muliby-lb** [comment]
Thanks @majst01 and @mwennrich , looks good to me.
@rahman-lb @yogev-lb @ron-lb any comments?

**Comment by majst01** [comment]
Regarding the still present mount problem, we face this with older version of the csi driver in the fleet and where hoping that this is fixed with v1.13 but isn't.

Any ideas howto identify the root cause of this problem ? I know this is unrelated to this PR

**Comment by lev-lb** [comment]
@sagi-lb , @yogev-lb : 
```
[Wed Jan 10 10:31:11 2024] nvme_fabrics: found same hostid
2b0bf3a6-721f-47f6-9fd7-ca3ffe410c1f but different hostnqn
nqn.2019-09.com.lightbitslabs:host:shoot--p4jxn2--mwentest-group-0-8558f-j992z.node
```
that rings a bell. didn't we have the same thing just the other day in OpenStack? isn't this a result of a backwards-incompatible change in the kernel (`hostid` vs `hostnqn`)?

**Comment by lev-lb** [comment]
@majst01 :

> Any ideas howto identify the root cause of this problem ? I know this is unrelated to this PR

what distro and kernel version are you using there? (see also above).

**Comment by sagi-lb** [comment]
> @sagi-lb , @yogev-lb :
> 
> ```
> [Wed Jan 10 10:31:11 2024] nvme_fabrics: found same hostid
> 2b0bf3a6-721f-47f6-9fd7-ca3ffe410c1f but different hostnqn
> nqn.2019-09.com.lightbitslabs:host:shoot--p4jxn2--mwentest-group-0-8558f-j992z.node
> ```
> 
> that rings a bell. didn't we have the same thing just the other day in OpenStack? isn't this a result of a backwards-incompatible change in the kernel (`hostid` vs `hostnqn`)?

Yes, indeed. This is relatively new to the change made recently. It broke several other userspace tools, and requires a fix. I know it is in the works.

**Comment by muliby-lb** [comment]
I thought per the latest on LBM1-30942 (sorry @majst01 and @mwennrich, that's Lightbits internal) the `discovery-client` is supposed to be immune to this issue because it uses the host's `/etc/nvme/hostid` and generates it if it's not found. @majst01 @mwennrich is it possible you have the same `/etc/nvme/hostid` on multiple systems?

**Comment by majst01** [comment]
> `/etc/nvme/hostid`

@muliby-lb will check for this and come back

**Comment by majst01** [comment]
> I thought per the latest on LBM1-30942 (sorry @majst01 and @mwennrich, that's Lightbits internal) the `discovery-client` is supposed to be immune to this issue because it uses the host's `/etc/nvme/hostid` and generates it if it's not found. @majst01 @mwennrich is it possible you have the same `/etc/nvme/hostid` on multiple systems?

This happened on a cluster with one single machine:

```
root@shoot--p4jxn2--mwentest-group-0-8558f-l8tk7:/etc/nvme# cat hostid 
3fde5db7-2722-4547-aa2f-254c0427738c
root@shoot--p4jxn2--mwentest-group-0-8558f-l8tk7:/etc/nvme# cat hostnqn 
nqn.2014-08.org.nvmexpress:uuid:84752463-8abe-4f48-91a8-024ddde406c2
root@shoot--p4jxn2--mwentest-group-0-8558f-l8tk7:/etc/nvme# hostname
shoot--p4jxn2--mwentest-group-0-8558f-l8tk7
```
Not sure how this hostid is calculated, i checked several machines, all different.
Is it a problem that hostid and hostname differ ?

**Comment by muliby-lb** [comment]
> > I thought per the latest on LBM1-30942 (sorry @majst01 and @mwennrich, that's Lightbits internal) the `discovery-client` is supposed to be immune to this issue because it uses the host's `/etc/nvme/hostid` and generates it if it's not found. @majst01 @mwennrich is it possible you have the same `/etc/nvme/hostid` on multiple systems?
> 
> This happened on a cluster with one single machine:
> 
> ```
> root@shoot--p4jxn2--mwentest-group-0-8558f-l8tk7:/etc/nvme# cat hostid 
> 3fde5db7-2722-4547-aa2f-254c0427738c
> root@shoot--p4jxn2--mwentest-group-0-8558f-l8tk7:/etc/nvme# cat hostnqn 
> nqn.2014-08.org.nvmexpress:uuid:84752463-8abe-4f48-91a8-024ddde406c2
> root@shoot--p4jxn2--mwentest-group-0-8558f-l8tk7:/etc/nvme# hostname
> shoot--p4jxn2--mwentest-group-0-8558f-l8tk7
> ```
> 
> Not sure how this hostid is calculated, i checked several machines, all different. Is it a problem that hostid and hostname differ ?

@guy-lb can you take a look and see whether this matches our understanding of the bug? (gentle reminder: this repo and all discussions on it are public and open to all)

**Comment by lev-lb** [comment]
@majst01 :

> Kernel is 6.6.10 and distro is ubuntu-22.04

do you observe this issue on kernels _prior to_ v6.5? because it kind of looks like:
```
commit ae8bd606e09bbdb2607c8249872cc2aeaf2fcc72
Author: Max Gurtovoy <mgurtovoy@nvidia.com>
Date:   Fri May 12 18:41:55 2023 +0300

    nvme-fabrics: prevent overriding of existing host
```
that was introduced in v6.5...

**Comment by muliby-lb** [comment]
@rahman-lb as the official owner of the CSI plugin, please review. (For what it's worth, looks fine to me.)

**Comment by muliby-lb** [comment]
Next steps on this one:
1. Run it in `lb-csi` and also with the `discovery-client` patch for hostid. Assuming it passes the tests (no reason why it shouldn't), merge it here and in `lb-csi`.
@majst01 after we merge it, do you need us to supply a new CSI plugin or are you running your own packages?

**Comment by majst01** [comment]
> Next steps on this one: run it in `lb-csi` and also with the `discovery-client` patch for hostid. Assuming it passes the tests (no reason why it shouldn't), merge it here and in `lb-csi`. @majst01 after we merge it, do you need us to supply a new CSI plugin or are you running your own packages?

We always run the package provided by you guys, we do not have our own pipeline for the csi driver, also there is no github action which creates the csi driver container here in this repo which pushes to a registry.

**Comment by muliby-lb** [comment]
Understood. We'll get a package for you in the next few days once we complete the testing and merge.

Getting this git repo to be self contained incuding CI and a CD pipeline is on our TODO, hopefully we'll get to it sooner rather than later.

**Pull request merged**
