### PR TITLE
Try to unmount when we get io-error from block-device 

### PR DESCRIPTION
**Pull request by rahman-lb**
Related lb-csi PR.  
https://github.com/LightBitsLabs/lb-csi/pull/181/files

we noticed that when we get to read-only state in lightbits we will send io-errors on writes to the file-system - may it be ext4 or xfs. this will cause the FS to shutdown and will not be usable without remounting and running fsck.

we noticed that when we try to unpublish and unstage the volume we would try to verify that the target is indeed a mount-point and we this will result in IO-error which will privent us from umounting and will cause the pod to stuck in terminating state forever.

in order to enable umounting the volume once the FS is in corrupted state, and we for sure can loose the cached-data cause it will not be written, we will ease the verification and if the folder exists but return io-error we will try to umount. if successful we will proceed otherwise we will return the error we get from umount.

issue: LBM1-33573

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved error handling for volume management operations, allowing unmounting to proceed under specific I/O error conditions.
	- Streamlined error checks related to mount points for enhanced robustness.

### CODE REVIEW

**Review by maor-lb — APPROVED** [review]

**Comment by ronen-lb** [comment]
@rahman-lb we want to bump version here too

**Comment by majst01** [comment]
I was already preparing a PR which replaces the deprecated `mounter.IsNotMounted` with a much better to read alternative. I can do this after this PR if you wish

**Comment by rahman-lb** [comment]
@majst01 feel free to places the deprecated mounter.IsNotMounted .

**Comment by rahman-lb** [comment]
@ronen-lb  we have not merged previous version bump into master, i'll create two PRs one for each version bump.

**Pull request merged**
