### PR TITLE
Ronen/update to 1 15

### PR DESCRIPTION
**Pull request by ronen-lb**
this is an incremental PR to:
https://github.com/LightBitsLabs/los-csi/pull/37
that bumps up the version

    * csi - 1.15.0
    * lb-csi-plugin helm chart - 0.13.0
    * lb-csi-workload-examples helm chart - 0.13.0
    * snapshot-controller-3 chart - 0.13.0
    * snapshot-controller-4 chart - 0.13.0
    * update docs to reference new version of lightbits (3.8.1) as well
       as csi plugin and helm chart.
    * add changelog: docs/src/CHANGELOG/CHANGELOG-1.15.0.md

### CODE REVIEW

**Comment by muliby-lb** [comment]
@ronen-lb what is `go-1.22` branch?

**Comment by majst01** [comment]
> @ronen-lb what is `go-1.22` branch?

This branch is from my PR #37

**Comment by rahman-lb** [comment]
@ronen-lb  https://github.com/LightBitsLabs/los-csi/pull/37  requires a passing test before merge, i'll hold off on this merge until tests are passed.

**Comment by ronen-lb** [comment]
@asafm-lb FYI

**Comment by rahman-lb** [comment]
It has passed  tests, and ready to be merged.

**Comment by rahman-lb** [comment]
@ronen-lb  I want to merge this PR, let me know if you have any concern .

**Pull request merged**
